In [29]:
import numpy as np
import pandas as pd

In [30]:
df = pd.read_csv(r"anime.csv")

In [49]:
dfa=df.head(20)

##feature extraction

In [37]:
df.loc[[6]]["title"]

6    Attack on Titan: The Final Season (16 eps)
Name: title, dtype: object

In [61]:
def ext_epi(txt):
  check = False ## check works as a switch
  data = ""
  for i in txt:
    if i ==")":
      check = False
      return data
    if check == True:
      data += i
    if i == "(":
      check = True

In [65]:
dfa["episodes"]= dfa["title"].apply(ext_epi)
dfa
dfa

/tmp/ipykernel_3003/939621344.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfa["episodes"]= dfa["title"].apply(ext_epi)

,rank,title,score,epispdes,episodes
0,1,Frieren: Beyond Journey's End (28 eps),9.3,28 eps,28 eps
1,2,Frieren: Beyond Journey's End Season 1 (28 eps),9.3,28 eps,28 eps
2,3,Attack on Titan: The Final Chapters (2 eps),9.1,2 eps,2 eps
3,4,Fullmetal Alchemist: Brotherhood (64 eps),9.1,64 eps,64 eps
4,5,Steins;Gate (24 eps),9.1,24 eps,24 eps
5,6,Attack on Titan (25 eps),9.0,25 eps,25 eps
6,7,Attack on Titan: The Final Season (16 eps),9.0,16 eps,16 eps
7,8,Gintama (201 eps),9.0,201 eps,201 eps
8,9,Hunter x Hunter (2011) (148 eps),9.0,2011,2011
9,10,One Piece (1150 eps),9.0,1150 eps,1150 eps
10,11,Bleach (366 eps),8.9,366 eps,366 eps
11,12,Clannad: After Story (24 eps),8.9,24 eps,24 eps
12,13,Kaguya-sama: Love Is War (12 eps),8.9,12 eps,12 eps
13,14,Mob Psycho 100 II (13 eps),8.9,13 eps,13 eps
14,15,The Apothecary Diaries (24 eps),8.9,24 eps,24 eps
15,16,Code Geass (25 eps),8.8,25 eps,25 eps
16,17,Jujutsu Kaisen Season 2 (23 eps),8.8,23 eps,23 eps
17,18,Mob Psycho 100 (12 eps),8.8,12 eps,12 eps
18,19,Monster (74 eps),8.8,74 eps,74 eps
19,20,The Apothecary Diaries Season 2 (24 eps),8.8,24 eps,24 eps

In [76]:
dfa["episodes"]=dfa['episodes'].astype(int)

/tmp/ipykernel_3003/1519248141.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfa["episodes"]=dfa['episodes'].astype(int)

In [71]:
dfa.loc[0]['title']

"Frieren: Beyond Journey's End (28 eps)"

In [83]:
dfa[dfa["score"]== dfa["score"].max()] ["title"]

0             Frieren: Beyond Journey's End (28 eps)
1    Frieren: Beyond Journey's End Season 1 (28 eps)
Name: title, dtype: object

In [90]:
dfa.head()["title"] # top 5 anime shows

0             Frieren: Beyond Journey's End (28 eps)
1    Frieren: Beyond Journey's End Season 1 (28 eps)
2        Attack on Titan: The Final Chapters (2 eps)
3          Fullmetal Alchemist: Brotherhood (64 eps)
4                               Steins;Gate (24 eps)
Name: title, dtype: object

In [93]:
dfa[dfa['episodes'] == dfa["episodes"].max()]["title"]

8    Hunter x Hunter (2011) (148 eps)
Name: title, dtype: object